use std::collections::BTreeMap;
use std::error::Error;
use std::fmt::Display;
use std::fs;
use std::fs::OpenOptions;
use std::io;
use std::io::BufWriter;
use std::io::Write;
use std::path::Path;
use std::path::PathBuf;
use std::sync::atomic::AtomicU64;
use std::sync::atomic::Ordering;

use serde::Deserialize;
use serde::Serialize;

use crate::ActionKind;
use crate::ActionTypeMetrics;
use crate::CountRatio;
use crate::DistributionMetrics;
use crate::GameMetrics;
use crate::MetricsError;
use crate::ReactionChangeMetrics;
use crate::record::ArenaManifest;
use crate::record::GameRecord;
use crate::record::GameResultRecord;
use crate::record::PhaseRecord;
use crate::record::PlayerRecord;
use crate::record::ScheduleRecord;
use crate::storage::DatasetError;
use crate::storage::JsonlDatasetReader;

/// Version of the persisted Arena analysis schema.
pub const ANALYSIS_SCHEMA_VERSION: u32 = 1;
/// Flat per-game metrics output generated by [`DatasetAnalyzer`].
pub const GAME_METRICS_FILE_NAME: &str = "game_metrics.csv";
/// Aggregate metrics output generated by [`DatasetAnalyzer`].
pub const SUMMARY_FILE_NAME: &str = "summary.json";

static NEXT_TEMPORARY_OUTPUT: AtomicU64 = AtomicU64::new(0);

/// Analyzes one complete persisted dataset without modifying its raw records.
#[derive(Debug, Copy, Clone, Default)]
pub struct DatasetAnalyzer;

impl DatasetAnalyzer {
    /// Replay every game and create `game_metrics.csv` plus `summary.json`.
    ///
    /// Existing derived outputs are never overwritten. Temporary files are
    /// removed when analysis returns an error.
    pub fn analyze(root: impl AsRef<Path>) -> Result<AnalysisReport, AnalysisError> {
        let mut reader = JsonlDatasetReader::open(root)?;
        let manifest = reader.manifest().clone();
        let dataset_root = reader.root().to_path_buf();
        let game_metrics_path = dataset_root.join(GAME_METRICS_FILE_NAME);
        let summary_path = dataset_root.join(SUMMARY_FILE_NAME);
        ensure_output_absent(&game_metrics_path)?;
        ensure_output_absent(&summary_path)?;

        let mut game_metrics_temp = TemporaryOutput::new(&dataset_root, GAME_METRICS_FILE_NAME);
        let game_metrics_file =
            OpenOptions::new().write(true).create_new(true).open(game_metrics_temp.path())?;
        let mut game_metrics_writer = BufWriter::new(game_metrics_file);
        write_csv_header(&mut game_metrics_writer)?;

        let mut accumulator = SummaryAccumulator::new(&manifest);
        for record in &mut reader {
            let record = record?;
            validate_record_dimensions(&manifest, &record)?;
            let metrics = GameMetrics::from_record(&record)?;
            write_game_metrics_row(&mut game_metrics_writer, &metrics)?;
            accumulator.record(&record, &metrics)?;
        }
        game_metrics_writer.flush()?;
        drop(game_metrics_writer);

        let games_analyzed = reader.read_games();
        let summary = accumulator.finish(&manifest);
        let mut summary_temp = TemporaryOutput::new(&dataset_root, SUMMARY_FILE_NAME);
        let summary_file =
            OpenOptions::new().write(true).create_new(true).open(summary_temp.path())?;
        let mut summary_writer = BufWriter::new(summary_file);
        serde_json::to_writer_pretty(&mut summary_writer, &summary)?;
        summary_writer.write_all(b"\n")?;
        summary_writer.flush()?;
        drop(summary_writer);

        game_metrics_temp.commit(&game_metrics_path)?;
        if let Err(error) = summary_temp.commit(&summary_path) {
            let _ = fs::remove_file(&game_metrics_path);
            return Err(AnalysisError::Io(error));
        }

        Ok(AnalysisReport { dataset_root, game_metrics_path, summary_path, games_analyzed })
    }
}

/// Files created by one completed analysis.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AnalysisReport {
    pub dataset_root: PathBuf,
    pub game_metrics_path: PathBuf,
    pub summary_path: PathBuf,
    pub games_analyzed: u64,
}

/// Deterministic aggregate metrics for one complete dataset.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DatasetSummary {
    pub schema_version: u32,
    pub arena_version: String,
    pub source_record_schema_version: u32,
    pub games: u64,
    pub results: ResultSummary,
    pub terminations: TerminationSummary,
    pub participant_a: ParticipantSummary,
    pub participant_b: ParticipantSummary,
    pub actions: ActionSummary,
    pub reactions: ReactionSummary,
    pub final_material: FinalMaterialSummary,
    pub states: StateSummary,
}

/// Game results measured against the total number of games.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ResultSummary {
    pub red_wins: CountRatio,
    pub black_wins: CountRatio,
    pub draws: CountRatio,
    pub unfinished: CountRatio,
}

/// Termination categories measured against the total number of games.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TerminationSummary {
    pub completed: CountRatio,
    pub action_limits: CountRatio,
    pub agent_failures: CountRatio,
}

/// Outcomes for one participant overall and in each color seat.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ParticipantSummary {
    pub participant_id: String,
    pub overall: ParticipantOutcomeSummary,
    pub as_red: ParticipantOutcomeSummary,
    pub as_black: ParticipantOutcomeSummary,
    pub agent_failures: CountRatio,
}

/// Win, loss, draw, and unfinished rates for a participant subset.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ParticipantOutcomeSummary {
    pub games: u64,
    pub wins: CountRatio,
    pub losses: CountRatio,
    pub draws: CountRatio,
    pub unfinished: CountRatio,
}

/// Aggregate action counts and exact distributions.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ActionSummary {
    pub total_actions: u64,
    pub all_per_game: PhaseActionDistributionSummary,
    pub red_per_game: PhaseActionDistributionSummary,
    pub black_per_game: PhaseActionDistributionSummary,
    pub action_types: ActionTypeMetrics,
    pub legal_movement_actions: DistributionMetrics,
}

/// Per-game distributions for total, placement, and movement actions.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PhaseActionDistributionSummary {
    pub total_actions: DistributionMetrics,
    pub placement_actions: DistributionMetrics,
    pub movement_actions: DistributionMetrics,
}

/// Reaction occupancy transitions as totals and per-game distributions.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ReactionSummary {
    pub totals: ReactionChangeMetrics,
    pub additions_per_game: DistributionMetrics,
    pub removals_per_game: DistributionMetrics,
    pub replacements_per_game: DistributionMetrics,
}

/// Exact per-game distributions of final board and pool material.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FinalMaterialSummary {
    pub board_total: DistributionMetrics,
    pub board_red: DistributionMetrics,
    pub board_black: DistributionMetrics,
    pub board_white: DistributionMetrics,
    pub red_pool: DistributionMetrics,
    pub black_pool: DistributionMetrics,
    pub white_pool: DistributionMetrics,
}

/// Aggregate and per-game state visit statistics.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StateSummary {
    pub totals: StateVisitTotals,
    pub total_visits_per_game: DistributionMetrics,
    pub unique_states_per_game: DistributionMetrics,
    pub repeated_visits_per_game: DistributionMetrics,
    pub unique_state_ratio_per_game: FloatDistributionMetrics,
}

/// State visits summed across games without deduplicating between games.
#[derive(Debug, Copy, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct StateVisitTotals {
    pub total_visits: u64,
    pub unique_states: u64,
    pub repeated_visits: u64,
    pub unique_state_ratio: Option<f64>,
}

/// Type-7 distribution for finite floating-point observations.
#[derive(Debug, Copy, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct FloatDistributionMetrics {
    pub count: u64,
    pub min: Option<f64>,
    pub max: Option<f64>,
    pub mean: Option<f64>,
    pub median: Option<f64>,
    pub p25: Option<f64>,
    pub p75: Option<f64>,
    pub p90: Option<f64>,
    pub p95: Option<f64>,
}

/// Failure to analyze or persist derived metrics.
#[derive(Debug)]
pub enum AnalysisError {
    OutputExists(PathBuf),
    InvalidRecord { game_id: u64, message: String },
    Dataset(DatasetError),
    Metrics(MetricsError),
    Json(serde_json::Error),
    Io(io::Error),
}

impl Display for AnalysisError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::OutputExists(path) => {
                write!(formatter, "analysis output already exists: {}", path.display())
            },
            Self::InvalidRecord { game_id, message } => {
                write!(formatter, "game {game_id} has invalid analysis dimensions: {message}")
            },
            Self::Dataset(error) => Display::fmt(error, formatter),
            Self::Metrics(error) => Display::fmt(error, formatter),
            Self::Json(error) => write!(formatter, "analysis JSON processing failed: {error}"),
            Self::Io(error) => write!(formatter, "analysis I/O failed: {error}"),
        }
    }
}

impl Error for AnalysisError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Dataset(error) => Some(error),
            Self::Metrics(error) => Some(error),
            Self::Json(error) => Some(error),
            Self::Io(error) => Some(error),
            Self::OutputExists(_) | Self::InvalidRecord { .. } => None,
        }
    }
}

impl From<DatasetError> for AnalysisError {
    fn from(error: DatasetError) -> Self {
        Self::Dataset(error)
    }
}

impl From<MetricsError> for AnalysisError {
    fn from(error: MetricsError) -> Self {
        Self::Metrics(error)
    }
}

impl From<serde_json::Error> for AnalysisError {
    fn from(error: serde_json::Error) -> Self {
        Self::Json(error)
    }
}

impl From<io::Error> for AnalysisError {
    fn from(error: io::Error) -> Self {
        Self::Io(error)
    }
}

#[derive(Debug, Copy, Clone)]
enum Seat {
    Red,
    Black,
}

#[derive(Debug, Copy, Clone)]
enum ParticipantOutcome {
    Win,
    Loss,
    Draw,
    Unfinished,
}

#[derive(Default)]
struct ResultAccumulator {
    red_wins: u64,
    black_wins: u64,
    draws: u64,
    unfinished: u64,
}

impl ResultAccumulator {
    fn record(&mut self, result: GameResultRecord) {
        match result {
            GameResultRecord::RedWin => self.red_wins += 1,
            GameResultRecord::BlackWin => self.black_wins += 1,
            GameResultRecord::Draw => self.draws += 1,
            GameResultRecord::Unfinished => self.unfinished += 1,
        }
    }

    fn finish(self, games: u64) -> ResultSummary {
        ResultSummary {
            red_wins: count_ratio(self.red_wins, games),
            black_wins: count_ratio(self.black_wins, games),
            draws: count_ratio(self.draws, games),
            unfinished: count_ratio(self.unfinished, games),
        }
    }
}

#[derive(Default)]
struct TerminationAccumulator {
    completed: u64,
    action_limits: u64,
    agent_failures: u64,
}

impl TerminationAccumulator {
    fn record(&mut self, termination: crate::TerminationKind) {
        match termination {
            crate::TerminationKind::Completed => self.completed += 1,
            crate::TerminationKind::ActionLimit { .. } => {
                self.action_limits += 1;
            },
            crate::TerminationKind::AgentFailure { .. } => self.agent_failures += 1,
        }
    }

    fn finish(self, games: u64) -> TerminationSummary {
        TerminationSummary {
            completed: count_ratio(self.completed, games),
            action_limits: count_ratio(self.action_limits, games),
            agent_failures: count_ratio(self.agent_failures, games),
        }
    }
}

#[derive(Default)]
struct OutcomeAccumulator {
    games: u64,
    wins: u64,
    losses: u64,
    draws: u64,
    unfinished: u64,
}

impl OutcomeAccumulator {
    fn record(&mut self, outcome: ParticipantOutcome) {
        self.games += 1;
        match outcome {
            ParticipantOutcome::Win => self.wins += 1,
            ParticipantOutcome::Loss => self.losses += 1,
            ParticipantOutcome::Draw => self.draws += 1,
            ParticipantOutcome::Unfinished => self.unfinished += 1,
        }
    }

    fn finish(self) -> ParticipantOutcomeSummary {
        ParticipantOutcomeSummary {
            games: self.games,
            wins: count_ratio(self.wins, self.games),
            losses: count_ratio(self.losses, self.games),
            draws: count_ratio(self.draws, self.games),
            unfinished: count_ratio(self.unfinished, self.games),
        }
    }
}

struct ParticipantAccumulator {
    participant_id: String,
    overall: OutcomeAccumulator,
    as_red: OutcomeAccumulator,
    as_black: OutcomeAccumulator,
    agent_failures: u64,
}

impl ParticipantAccumulator {
    fn new(participant_id: String) -> Self {
        Self {
            participant_id,
            overall: OutcomeAccumulator::default(),
            as_red: OutcomeAccumulator::default(),
            as_black: OutcomeAccumulator::default(),
            agent_failures: 0,
        }
    }

    fn record(&mut self, seat: Seat, outcome: ParticipantOutcome) {
        self.overall.record(outcome);
        match seat {
            Seat::Red => self.as_red.record(outcome),
            Seat::Black => self.as_black.record(outcome),
        }
    }

    fn finish(self) -> ParticipantSummary {
        let games = self.overall.games;
        ParticipantSummary {
            participant_id: self.participant_id,
            overall: self.overall.finish(),
            as_red: self.as_red.finish(),
            as_black: self.as_black.finish(),
            agent_failures: count_ratio(self.agent_failures, games),
        }
    }
}

#[derive(Default)]
struct IntegerDistributionAccumulator {
    frequencies: BTreeMap<u64, u64>,
    count: u64,
    sum: f64,
}

impl IntegerDistributionAccumulator {
    fn record(&mut self, value: u64) {
        *self.frequencies.entry(value).or_default() += 1;
        self.count += 1;
        self.sum += value as f64;
    }

    fn finish(self) -> DistributionMetrics {
        if self.count == 0 {
            return DistributionMetrics::default();
        }
        let min = self.frequencies.first_key_value().map(|(&value, _)| value);
        let max = self.frequencies.last_key_value().map(|(&value, _)| value);
        DistributionMetrics {
            count: self.count,
            min,
            max,
            mean: Some(self.sum / self.count as f64),
            median: Some(self.percentile(0.5)),
            p25: Some(self.percentile(0.25)),
            p75: Some(self.percentile(0.75)),
            p90: Some(self.percentile(0.9)),
            p95: Some(self.percentile(0.95)),
        }
    }

    fn percentile(&self, probability: f64) -> f64 {
        let index = (self.count - 1) as f64 * probability;
        let lower_rank = index.floor() as u64;
        let upper_rank = index.ceil() as u64;
        let lower = self.value_at_rank(lower_rank) as f64;
        let upper = self.value_at_rank(upper_rank) as f64;
        lower + (upper - lower) * (index - lower_rank as f64)
    }

    fn value_at_rank(&self, rank: u64) -> u64 {
        let mut remaining = rank;
        for (&value, &frequency) in &self.frequencies {
            if remaining < frequency {
                return value;
            }
            remaining -= frequency;
        }
        unreachable!("rank is bounded by the recorded observation count")
    }
}

#[derive(Default)]
struct FloatDistributionAccumulator {
    values: Vec<f64>,
}

impl FloatDistributionAccumulator {
    fn record(&mut self, value: f64) {
        debug_assert!(value.is_finite(), "state ratios must be finite");
        self.values.push(value);
    }

    fn finish(mut self) -> FloatDistributionMetrics {
        self.values.sort_by(f64::total_cmp);
        let Some(&min) = self.values.first() else {
            return FloatDistributionMetrics::default();
        };
        let max = self.values[self.values.len() - 1];
        let count = self.values.len() as u64;
        let mean = self.values.iter().sum::<f64>() / count as f64;
        FloatDistributionMetrics {
            count,
            min: Some(min),
            max: Some(max),
            mean: Some(mean),
            median: Some(float_percentile(&self.values, 0.5)),
            p25: Some(float_percentile(&self.values, 0.25)),
            p75: Some(float_percentile(&self.values, 0.75)),
            p90: Some(float_percentile(&self.values, 0.9)),
            p95: Some(float_percentile(&self.values, 0.95)),
        }
    }
}

#[derive(Default)]
struct PhaseActionDistributionAccumulator {
    total_actions: IntegerDistributionAccumulator,
    placement_actions: IntegerDistributionAccumulator,
    movement_actions: IntegerDistributionAccumulator,
}

impl PhaseActionDistributionAccumulator {
    fn record(&mut self, total: u64, placement: u64, movement: u64) {
        self.total_actions.record(total);
        self.placement_actions.record(placement);
        self.movement_actions.record(movement);
    }

    fn finish(self) -> PhaseActionDistributionSummary {
        PhaseActionDistributionSummary {
            total_actions: self.total_actions.finish(),
            placement_actions: self.placement_actions.finish(),
            movement_actions: self.movement_actions.finish(),
        }
    }
}

#[derive(Default)]
struct ActionTypeAccumulator {
    total_actions: u64,
    placements: u64,
    moves: u64,
    captures: u64,
    pushes: u64,
    draws: u64,
    divides: u64,
    passes: u64,
    resignations: u64,
}

impl ActionTypeAccumulator {
    fn record(&mut self, metrics: &ActionTypeMetrics) {
        self.total_actions += metrics.total_actions;
        self.placements += metrics.placements.count;
        self.moves += metrics.moves.count;
        self.captures += metrics.captures.count;
        self.pushes += metrics.pushes.count;
        self.draws += metrics.draws.count;
        self.divides += metrics.divides.count;
        self.passes += metrics.passes.count;
        self.resignations += metrics.resignations.count;
    }

    fn finish(self) -> ActionTypeMetrics {
        ActionTypeMetrics {
            total_actions: self.total_actions,
            placements: count_ratio(self.placements, self.total_actions),
            moves: count_ratio(self.moves, self.total_actions),
            captures: count_ratio(self.captures, self.total_actions),
            pushes: count_ratio(self.pushes, self.total_actions),
            draws: count_ratio(self.draws, self.total_actions),
            divides: count_ratio(self.divides, self.total_actions),
            passes: count_ratio(self.passes, self.total_actions),
            resignations: count_ratio(self.resignations, self.total_actions),
        }
    }
}

#[derive(Default)]
struct ActionAccumulator {
    all_per_game: PhaseActionDistributionAccumulator,
    red_per_game: PhaseActionDistributionAccumulator,
    black_per_game: PhaseActionDistributionAccumulator,
    action_types: ActionTypeAccumulator,
    legal_movement_actions: IntegerDistributionAccumulator,
}

impl ActionAccumulator {
    fn record(&mut self, record: &GameRecord, metrics: &GameMetrics) {
        let red = &metrics.actions_by_side.red;
        let black = &metrics.actions_by_side.black;
        self.all_per_game.record(
            metrics.action_types.total_actions,
            red.placement_actions + black.placement_actions,
            red.movement_actions + black.movement_actions,
        );
        self.red_per_game.record(red.total_actions, red.placement_actions, red.movement_actions);
        self.black_per_game.record(
            black.total_actions,
            black.placement_actions,
            black.movement_actions,
        );
        self.action_types.record(&metrics.action_types);
        for legal_count in record.actions.iter().filter_map(|action| action.legal_action_count) {
            self.legal_movement_actions.record(legal_count);
        }
    }

    fn finish(self) -> ActionSummary {
        let action_types = self.action_types.finish();
        ActionSummary {
            total_actions: action_types.total_actions,
            all_per_game: self.all_per_game.finish(),
            red_per_game: self.red_per_game.finish(),
            black_per_game: self.black_per_game.finish(),
            action_types,
            legal_movement_actions: self.legal_movement_actions.finish(),
        }
    }
}

#[derive(Default)]
struct ReactionAccumulator {
    totals: ReactionChangeMetrics,
    additions_per_game: IntegerDistributionAccumulator,
    removals_per_game: IntegerDistributionAccumulator,
    replacements_per_game: IntegerDistributionAccumulator,
}

impl ReactionAccumulator {
    fn record(&mut self, metrics: &ReactionChangeMetrics) {
        self.totals.additions += metrics.additions;
        self.totals.removals += metrics.removals;
        self.totals.replacements += metrics.replacements;
        self.additions_per_game.record(metrics.additions);
        self.removals_per_game.record(metrics.removals);
        self.replacements_per_game.record(metrics.replacements);
    }

    fn finish(self) -> ReactionSummary {
        ReactionSummary {
            totals: self.totals,
            additions_per_game: self.additions_per_game.finish(),
            removals_per_game: self.removals_per_game.finish(),
            replacements_per_game: self.replacements_per_game.finish(),
        }
    }
}

#[derive(Default)]
struct FinalMaterialAccumulator {
    board_total: IntegerDistributionAccumulator,
    board_red: IntegerDistributionAccumulator,
    board_black: IntegerDistributionAccumulator,
    board_white: IntegerDistributionAccumulator,
    red_pool: IntegerDistributionAccumulator,
    black_pool: IntegerDistributionAccumulator,
    white_pool: IntegerDistributionAccumulator,
}

impl FinalMaterialAccumulator {
    fn record(&mut self, metrics: &crate::FinalMaterialMetrics) {
        self.board_total.record(metrics.board_pieces.total);
        self.board_red.record(metrics.board_pieces.red);
        self.board_black.record(metrics.board_pieces.black);
        self.board_white.record(metrics.board_pieces.white);
        self.red_pool.record(metrics.red_pool_pieces);
        self.black_pool.record(metrics.black_pool_pieces);
        self.white_pool.record(metrics.white_pool_pieces);
    }

    fn finish(self) -> FinalMaterialSummary {
        FinalMaterialSummary {
            board_total: self.board_total.finish(),
            board_red: self.board_red.finish(),
            board_black: self.board_black.finish(),
            board_white: self.board_white.finish(),
            red_pool: self.red_pool.finish(),
            black_pool: self.black_pool.finish(),
            white_pool: self.white_pool.finish(),
        }
    }
}

#[derive(Default)]
struct StateAccumulator {
    totals: StateVisitTotals,
    total_visits_per_game: IntegerDistributionAccumulator,
    unique_states_per_game: IntegerDistributionAccumulator,
    repeated_visits_per_game: IntegerDistributionAccumulator,
    unique_state_ratio_per_game: FloatDistributionAccumulator,
}

impl StateAccumulator {
    fn record(&mut self, metrics: &crate::StateVisitMetrics) {
        self.totals.total_visits += metrics.total_visits;
        self.totals.unique_states += metrics.unique_states;
        self.totals.repeated_visits += metrics.repeated_visits;
        self.total_visits_per_game.record(metrics.total_visits);
        self.unique_states_per_game.record(metrics.unique_states);
        self.repeated_visits_per_game.record(metrics.repeated_visits);
        self.unique_state_ratio_per_game.record(metrics.unique_state_ratio);
    }

    fn finish(mut self) -> StateSummary {
        self.totals.unique_state_ratio = if self.totals.total_visits == 0 {
            None
        } else {
            Some(self.totals.unique_states as f64 / self.totals.total_visits as f64)
        };
        StateSummary {
            totals: self.totals,
            total_visits_per_game: self.total_visits_per_game.finish(),
            unique_states_per_game: self.unique_states_per_game.finish(),
            repeated_visits_per_game: self.repeated_visits_per_game.finish(),
            unique_state_ratio_per_game: self.unique_state_ratio_per_game.finish(),
        }
    }
}

struct SummaryAccumulator {
    games: u64,
    results: ResultAccumulator,
    terminations: TerminationAccumulator,
    participant_a: ParticipantAccumulator,
    participant_b: ParticipantAccumulator,
    actions: ActionAccumulator,
    reactions: ReactionAccumulator,
    final_material: FinalMaterialAccumulator,
    states: StateAccumulator,
}

impl SummaryAccumulator {
    fn new(manifest: &ArenaManifest) -> Self {
        Self {
            games: 0,
            results: ResultAccumulator::default(),
            terminations: TerminationAccumulator::default(),
            participant_a: ParticipantAccumulator::new(manifest.participant_a.id.clone()),
            participant_b: ParticipantAccumulator::new(manifest.participant_b.id.clone()),
            actions: ActionAccumulator::default(),
            reactions: ReactionAccumulator::default(),
            final_material: FinalMaterialAccumulator::default(),
            states: StateAccumulator::default(),
        }
    }

    fn record(&mut self, record: &GameRecord, metrics: &GameMetrics) -> Result<(), AnalysisError> {
        self.games += 1;
        self.results.record(metrics.result);
        self.terminations.record(metrics.termination);
        let (red_outcome, black_outcome) = participant_outcomes(metrics.result);
        self.participant_mut(&metrics.red_participant_id, metrics.game_id)?
            .record(Seat::Red, red_outcome);
        self.participant_mut(&metrics.black_participant_id, metrics.game_id)?
            .record(Seat::Black, black_outcome);
        if let crate::TerminationKind::AgentFailure { player, .. } = metrics.termination {
            let participant_id = match player {
                PlayerRecord::Red => &metrics.red_participant_id,
                PlayerRecord::Black => &metrics.black_participant_id,
            };
            self.participant_mut(participant_id, metrics.game_id)?.agent_failures += 1;
        }
        self.actions.record(record, metrics);
        self.reactions.record(&metrics.reaction_changes);
        self.final_material.record(&metrics.final_material);
        self.states.record(&metrics.state_visits);
        Ok(())
    }

    fn finish(self, manifest: &ArenaManifest) -> DatasetSummary {
        DatasetSummary {
            schema_version: ANALYSIS_SCHEMA_VERSION,
            arena_version: crate::VERSION.to_owned(),
            source_record_schema_version: manifest.schema_version,
            games: self.games,
            results: self.results.finish(self.games),
            terminations: self.terminations.finish(self.games),
            participant_a: self.participant_a.finish(),
            participant_b: self.participant_b.finish(),
            actions: self.actions.finish(),
            reactions: self.reactions.finish(),
            final_material: self.final_material.finish(),
            states: self.states.finish(),
        }
    }

    fn participant_mut(
        &mut self, participant_id: &str, game_id: u64,
    ) -> Result<&mut ParticipantAccumulator, AnalysisError> {
        if self.participant_a.participant_id == participant_id {
            Ok(&mut self.participant_a)
        } else if self.participant_b.participant_id == participant_id {
            Ok(&mut self.participant_b)
        } else {
            Err(AnalysisError::InvalidRecord {
                game_id,
                message: format!("unknown participant {participant_id:?}"),
            })
        }
    }
}

struct TemporaryOutput {
    path: PathBuf,
    committed: bool,
}

impl TemporaryOutput {
    fn new(root: &Path, output_name: &str) -> Self {
        let unique = NEXT_TEMPORARY_OUTPUT.fetch_add(1, Ordering::Relaxed);
        let path = root.join(format!(".{output_name}.{}.{}.tmp", std::process::id(), unique));
        Self { path, committed: false }
    }

    fn path(&self) -> &Path {
        &self.path
    }

    fn commit(&mut self, destination: &Path) -> io::Result<()> {
        fs::rename(&self.path, destination)?;
        self.committed = true;
        Ok(())
    }
}

impl Drop for TemporaryOutput {
    fn drop(&mut self) {
        if !self.committed {
            let _ = fs::remove_file(&self.path);
        }
    }
}

#[derive(Debug)]
enum CsvField {
    Raw(String),
    Text(String),
    Empty,
}

const CSV_COLUMNS: &[&str] = &[
    "game_id",
    "pair_id",
    "game_in_pair",
    "red_participant_id",
    "black_participant_id",
    "result",
    "termination_kind",
    "termination_limit",
    "termination_player",
    "termination_phase",
    "last_action_index",
    "last_action_player",
    "last_action_phase",
    "last_action_kind",
    "last_action_notation",
    "red_total_actions",
    "red_placement_actions",
    "red_movement_actions",
    "black_total_actions",
    "black_placement_actions",
    "black_movement_actions",
    "total_actions",
    "placements_count",
    "placements_ratio",
    "moves_count",
    "moves_ratio",
    "captures_count",
    "captures_ratio",
    "pushes_count",
    "pushes_ratio",
    "draws_count",
    "draws_ratio",
    "divides_count",
    "divides_ratio",
    "passes_count",
    "passes_ratio",
    "resignations_count",
    "resignations_ratio",
    "legal_movement_count",
    "legal_movement_min",
    "legal_movement_max",
    "legal_movement_mean",
    "legal_movement_median",
    "legal_movement_p25",
    "legal_movement_p75",
    "legal_movement_p90",
    "legal_movement_p95",
    "reaction_additions",
    "reaction_removals",
    "reaction_replacements",
    "final_board_total",
    "final_board_red",
    "final_board_black",
    "final_board_white",
    "final_red_pool",
    "final_black_pool",
    "final_white_pool",
    "state_total_visits",
    "state_unique_states",
    "state_repeated_visits",
    "state_unique_ratio",
];

fn write_csv_header(writer: &mut impl Write) -> io::Result<()> {
    writer.write_all(CSV_COLUMNS.join(",").as_bytes())?;
    writer.write_all(b"\n")
}

fn write_game_metrics_row(writer: &mut impl Write, metrics: &GameMetrics) -> io::Result<()> {
    let mut fields = Vec::with_capacity(CSV_COLUMNS.len());
    fields.push(raw(metrics.game_id));
    fields.push(optional_raw(metrics.pair_id));
    fields.push(optional_raw(metrics.game_in_pair));
    fields.push(text(&metrics.red_participant_id));
    fields.push(text(&metrics.black_participant_id));
    fields.push(text(game_result_name(metrics.result)));
    push_termination_fields(&mut fields, metrics.termination);
    push_last_action_fields(&mut fields, metrics.last_action.as_ref());
    fields.push(raw(metrics.actions_by_side.red.total_actions));
    fields.push(raw(metrics.actions_by_side.red.placement_actions));
    fields.push(raw(metrics.actions_by_side.red.movement_actions));
    fields.push(raw(metrics.actions_by_side.black.total_actions));
    fields.push(raw(metrics.actions_by_side.black.placement_actions));
    fields.push(raw(metrics.actions_by_side.black.movement_actions));
    fields.push(raw(metrics.action_types.total_actions));
    push_count_ratio_fields(&mut fields, metrics.action_types.placements);
    push_count_ratio_fields(&mut fields, metrics.action_types.moves);
    push_count_ratio_fields(&mut fields, metrics.action_types.captures);
    push_count_ratio_fields(&mut fields, metrics.action_types.pushes);
    push_count_ratio_fields(&mut fields, metrics.action_types.draws);
    push_count_ratio_fields(&mut fields, metrics.action_types.divides);
    push_count_ratio_fields(&mut fields, metrics.action_types.passes);
    push_count_ratio_fields(&mut fields, metrics.action_types.resignations);
    push_distribution_fields(&mut fields, metrics.legal_movement_actions);
    fields.push(raw(metrics.reaction_changes.additions));
    fields.push(raw(metrics.reaction_changes.removals));
    fields.push(raw(metrics.reaction_changes.replacements));
    fields.push(raw(metrics.final_material.board_pieces.total));
    fields.push(raw(metrics.final_material.board_pieces.red));
    fields.push(raw(metrics.final_material.board_pieces.black));
    fields.push(raw(metrics.final_material.board_pieces.white));
    fields.push(raw(metrics.final_material.red_pool_pieces));
    fields.push(raw(metrics.final_material.black_pool_pieces));
    fields.push(raw(metrics.final_material.white_pool_pieces));
    fields.push(raw(metrics.state_visits.total_visits));
    fields.push(raw(metrics.state_visits.unique_states));
    fields.push(raw(metrics.state_visits.repeated_visits));
    fields.push(raw(metrics.state_visits.unique_state_ratio));
    write_csv_row(writer, &fields)
}

fn push_termination_fields(fields: &mut Vec<CsvField>, termination: crate::TerminationKind) {
    match termination {
        crate::TerminationKind::Completed => {
            fields.push(text("completed"));
            fields.extend([CsvField::Empty, CsvField::Empty, CsvField::Empty]);
        },
        crate::TerminationKind::ActionLimit { limit } => {
            fields.push(text("action_limit"));
            fields.push(raw(limit));
            fields.extend([CsvField::Empty, CsvField::Empty]);
        },
        crate::TerminationKind::AgentFailure { player, phase } => {
            fields.push(text("agent_failure"));
            fields.push(CsvField::Empty);
            fields.push(text(player_name(player)));
            fields.push(text(phase_name(phase)));
        },
    }
}

fn push_last_action_fields(fields: &mut Vec<CsvField>, action: Option<&crate::LastActionMetrics>) {
    let Some(action) = action else {
        fields.extend([
            CsvField::Empty,
            CsvField::Empty,
            CsvField::Empty,
            CsvField::Empty,
            CsvField::Empty,
        ]);
        return;
    };
    fields.push(raw(action.action_index));
    fields.push(text(player_name(action.player)));
    fields.push(text(phase_name(action.phase)));
    fields.push(text(action_kind_name(action.action_kind)));
    fields.push(text(&action.notation));
}

fn push_count_ratio_fields(fields: &mut Vec<CsvField>, ratio: CountRatio) {
    fields.push(raw(ratio.count));
    fields.push(optional_raw(ratio.ratio));
}

fn push_distribution_fields(fields: &mut Vec<CsvField>, distribution: DistributionMetrics) {
    fields.push(raw(distribution.count));
    fields.push(optional_raw(distribution.min));
    fields.push(optional_raw(distribution.max));
    fields.push(optional_raw(distribution.mean));
    fields.push(optional_raw(distribution.median));
    fields.push(optional_raw(distribution.p25));
    fields.push(optional_raw(distribution.p75));
    fields.push(optional_raw(distribution.p90));
    fields.push(optional_raw(distribution.p95));
}

fn write_csv_row(writer: &mut impl Write, fields: &[CsvField]) -> io::Result<()> {
    if fields.len() != CSV_COLUMNS.len() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("CSV row has {} fields, expected {}", fields.len(), CSV_COLUMNS.len()),
        ));
    }
    for (index, field) in fields.iter().enumerate() {
        if index != 0 {
            writer.write_all(b",")?;
        }
        match field {
            CsvField::Raw(value) => writer.write_all(value.as_bytes())?,
            CsvField::Text(value) => {
                writer.write_all(b"\"")?;
                writer.write_all(value.replace('"', "\"\"").as_bytes())?;
                writer.write_all(b"\"")?;
            },
            CsvField::Empty => {},
        }
    }
    writer.write_all(b"\n")
}

fn raw(value: impl Display) -> CsvField {
    CsvField::Raw(value.to_string())
}

fn optional_raw(value: Option<impl Display>) -> CsvField {
    value.map_or(CsvField::Empty, raw)
}

fn text(value: &str) -> CsvField {
    CsvField::Text(value.to_owned())
}

fn count_ratio(count: u64, total: u64) -> CountRatio {
    let ratio = if total == 0 { None } else { Some(count as f64 / total as f64) };
    CountRatio { count, ratio }
}

fn participant_outcomes(result: GameResultRecord) -> (ParticipantOutcome, ParticipantOutcome) {
    match result {
        GameResultRecord::RedWin => (ParticipantOutcome::Win, ParticipantOutcome::Loss),
        GameResultRecord::BlackWin => (ParticipantOutcome::Loss, ParticipantOutcome::Win),
        GameResultRecord::Draw => (ParticipantOutcome::Draw, ParticipantOutcome::Draw),
        GameResultRecord::Unfinished => {
            (ParticipantOutcome::Unfinished, ParticipantOutcome::Unfinished)
        },
    }
}

fn float_percentile(sorted: &[f64], probability: f64) -> f64 {
    debug_assert!(!sorted.is_empty(), "percentiles require at least one observation");
    let index = (sorted.len() - 1) as f64 * probability;
    let lower = index.floor() as usize;
    let upper = index.ceil() as usize;
    sorted[lower] + (sorted[upper] - sorted[lower]) * (index - lower as f64)
}

fn ensure_output_absent(path: &Path) -> Result<(), AnalysisError> {
    if path.exists() { Err(AnalysisError::OutputExists(path.to_path_buf())) } else { Ok(()) }
}

fn validate_record_dimensions(
    manifest: &ArenaManifest, record: &GameRecord,
) -> Result<(), AnalysisError> {
    let participant_a = manifest.participant_a.id.as_str();
    let participant_b = manifest.participant_b.id.as_str();
    let valid = match manifest.schedule {
        ScheduleRecord::Fixed { .. } => {
            record.pair_id.is_none()
                && record.game_in_pair.is_none()
                && record.red.participant_id == participant_a
                && record.black.participant_id == participant_b
        },
        ScheduleRecord::Paired { .. } => {
            let pair_id = record.game_id / 2;
            let game_in_pair = (record.game_id % 2) as u8;
            let seats_match = if game_in_pair == 0 {
                record.red.participant_id == participant_a
                    && record.black.participant_id == participant_b
            } else {
                record.red.participant_id == participant_b
                    && record.black.participant_id == participant_a
            };
            record.pair_id == Some(pair_id)
                && record.game_in_pair == Some(game_in_pair)
                && seats_match
        },
    };
    if valid {
        Ok(())
    } else {
        Err(AnalysisError::InvalidRecord {
            game_id: record.game_id,
            message: "pair or participant seats differ from the manifest schedule".to_owned(),
        })
    }
}

const fn game_result_name(result: GameResultRecord) -> &'static str {
    match result {
        GameResultRecord::Unfinished => "unfinished",
        GameResultRecord::RedWin => "red_win",
        GameResultRecord::BlackWin => "black_win",
        GameResultRecord::Draw => "draw",
    }
}

const fn player_name(player: PlayerRecord) -> &'static str {
    match player {
        PlayerRecord::Red => "red",
        PlayerRecord::Black => "black",
    }
}

const fn phase_name(phase: PhaseRecord) -> &'static str {
    match phase {
        PhaseRecord::Placement => "placement",
        PhaseRecord::Movement => "movement",
    }
}

const fn action_kind_name(action: ActionKind) -> &'static str {
    match action {
        ActionKind::Place => "place",
        ActionKind::Move => "move",
        ActionKind::Capture => "capture",
        ActionKind::Push => "push",
        ActionKind::Draw => "draw",
        ActionKind::Divide => "divide",
        ActionKind::Pass => "pass",
        ActionKind::Resign => "resign",
    }
}
